u20551101_HW03/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u20551101_HW03.Models;
using System.Text;
using System.IO;


namespace u20551101_HW03.Controllers
{
    public class HomeController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        public ActionResult Index(int studentpage = 1, int bookpage = 1)
        {
            int pageSize = 10;
            int studentSkipCount = (studentpage - 1) * pageSize;
            int bookSkipCount = (bookpage - 1) * pageSize;

            var students = db.students.OrderBy(s => s.studentId).Skip(studentSkipCount).Take(pageSize).ToList();
            var books = db.books.OrderBy(b => b.bookId).Skip(bookSkipCount).Take(pageSize).ToList();

            int studentTotalCount = db.students.Count();
            int bookTotalCount = db.books.Count();
            int studentTotalPages = (int)Math.Ceiling((double)studentTotalCount / pageSize);
            int bookTotalPages = (int)Math.Ceiling((double)bookTotalCount / pageSize);

            ViewBag.Books = books.Select(b => new SelectListItem
            {
                Value = b.authorId.ToString(),
                Text = b.authors.name
            }).ToList();

            ViewBag.Books = books.Select(b => new SelectListItem
            {
                Value = b.typeId.ToString(),
                Text = b.types.name
            }).ToList();



            ViewBag.Books = books;
            ViewBag.Students = students;
            ViewBag.StudentCurrentPage = studentpage;
            ViewBag.BookCurrentPage = bookpage;
            ViewBag.StudentTotalPages = studentTotalPages;
            ViewBag.BookTotalPages = bookTotalPages;
            return View();
        }

        public ActionResult Maintain(int authorpage = 1, int typepage = 1, int borrowpage = 1)
        {
            int pageSize = 10;

            int authorSkipCount = (authorpage - 1) * pageSize;
            int typeSkipCount = (typepage - 1) * pageSize;
            int borrowSkipCount = (borrowpage - 1) * pageSize;

            int authorTotalCount = db.authors.Count();
            int typeTotalCount = db.types.Count();
            int borrowTotalCount = db.borrows.Count();

            var authors = db.authors.OrderBy(a => a.name).Skip(authorSkipCount).Take(pageSize).ToList();

            var types = db.types.OrderBy(t => t.name).Skip(typeSkipCount).Take(pageSize).ToList();

            var borrows = db.borrows
    .Join(db.students, b => b.studentId, s => s.studentId, (b, student) => new { Borrow = b, StudentName = student.name })
    .OrderBy(b => b.StudentName)
    .Select(b => b.Borrow)
    .Skip(borrowSkipCount)
    .Take(pageSize)
    .ToList();



            int authorTotalPages = (int)Math.Ceiling((double)authorTotalCount / pageSize);
            int typeTotalPages = (int)Math.Ceiling((double)typeTotalCount / pageSize);
            int borrowTotalPages = (int)Math.Ceiling((double)borrowTotalCount / pageSize);




            ViewBag.Borrows = borrows.Select(b => new SelectListItem
            {
                Value = b.studentId.ToString(),
                Text = b.students.name + " " + b.students.surname
            }).ToList();

            ViewBag.Borrows = borrows.Select(b => new SelectListItem
            {
                Value = b.bookId.ToString(),
                Text = b.books.name
            }).ToList();

            ViewBag.Borrows = borrows;
            ViewBag.Authors = authors;
            ViewBag.Types = types;

            ViewBag.AuthorCurrentPage = authorpage;
            ViewBag.TypeCurrentPage = typepage;
            ViewBag.BorrowCurrentPage = borrowpage;

            ViewBag.AuthorTotalPages = authorTotalPages;
            ViewBag.TypeTotalPages = typeTotalPages;
            ViewBag.BorrowTotalPages = borrowTotalPages;

            return View();
        }

        public ActionResult Report()
        {
            var bookCounts = db.borrows
                .Where(b => b.takenDate.HasValue && b.takenDate.Value.Year >= 2015 && b.takenDate.Value.Year <= 2017)
                .GroupBy(b => new
                {
                    Year = b.takenDate.Value.Year,
                    BookName = b.books.name
                })
                .Select(group => new
                {
                    Year = group.Key.Year,
                    BookName = group.Key.BookName,
                    BorrowCount = group.Count()
                })
                .ToList();

            var labels = bookCounts.Select(b => b.BookName).Distinct().ToArray();
            var year2015Data = bookCounts.Where(b => b.Year == 2015).Select(b => b.BorrowCount).ToArray();
            var year2016Data = bookCounts.Where(b => b.Year == 2016).Select(b => b.BorrowCount).ToArray();
            var year2017Data = bookCounts.Where(b => b.Year == 2017).Select(b => b.BorrowCount).ToArray();

            ViewBag.ChartLabels = labels;
            ViewBag.Year2015Data = year2015Data;
            ViewBag.Year2016Data = year2016Data;
            ViewBag.Year2017Data = year2017Data;

            return View();
        }
     

    }
}

u20551101_HW03/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u20551101_HW03.Models;

namespace u20551101_HW03.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId,Status")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId,Status")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20551101_HW03/Controllers/studentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u20551101_HW03.Models;

namespace u20551101_HW03.Controllers
{
    public class studentsController : Controller
    {
        private LibraryEntities db = new LibraryEntities();

        // GET: students
        public async Task<ActionResult> Index()
        {
            return View(await db.students.ToListAsync());
        }

        // GET: students/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // GET: students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.students.Add(students);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(students);
        }

        // GET: students/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "studentId,name,surname,birthdate,gender,class,point")] students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(students);
        }

        // GET: students/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            students students = await db.students.FindAsync(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            students students = await db.students.FindAsync(id);
            db.students.Remove(students);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

u20551101_HW03/Views/Home/Index.cshtml
@model u20551101_HW03.Models.Merged
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<style>

    body {
        
        background-image: url("data:image/svg+xml,%3Csvg width='40' height='40' viewBox='0 0 40 40' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M20 20.5V18H0v-2h20v-2H0v-2h20v-2H0V8h20V6H0V4h20V2H0V0h22v20h2V0h2v20h2V0h2v20h2V0h2v20h2V0h2v20h2v2H20v-1.5zM0 20h2v20H0V20zm4 0h2v20H4V20zm4 0h2v20H8V20zm4 0h2v20h-2V20zm4 0h2v20h-2V20zm4 4h20v2H20v-2zm0 4h20v2H20v-2zm0 4h20v2H20v-2zm0 4h20v2H20v-2z' fill='%23aca292' fill-opacity='0.4' fill-rule='evenodd'/%3E%3C/svg%3E");
    }
    #myModal .navbar {
        display: none;
    }
    
    


</style>

<div class="container">
    <div class="row">
        <!-- Students Section -->
        <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">Students</h5>
                <div class="card-body">
                    <button class="btn btn-secondary float-right create-link" data-url="@Url.Action("Create", "students")">Create New</button>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Surname</th>
                                <th>Birthdate</th>
                                <th>Gender</th>
                                <th>Class</th>
                                <th>Point</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.Students)
                            {
                                <tr>
                                    <td>@item.name</td>
                                    <td>@item.surname</td>
                                    <td>@item.birthdate</td>
                                    <td>@item.gender</td>
                                    <td>@item.classname</td>
                                    <td>@item.point</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer pagination-container">
                    <!-- Pagination for Students -->
                    <ul class="pagination">
                        <li class="page-item @(ViewBag.StudentCurrentPage == 1 ? "disabled" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { studentpage = ViewBag.StudentCurrentPage - 1, bookpage = ViewBag.BookCurrentPage })">Previous</a>
                        </li>
                        @for (int i = Math.Max(1, ViewBag.StudentCurrentPage - 2); i <= Math.Min(ViewBag.StudentTotalPages, ViewBag.StudentCurrentPage + 2); i++)
                        {
                            <li class="page-item @(i == ViewBag.StudentCurrentPage ? "active" : "")">
                                <a class="page-link" href="@Url.Action("Index", new { studentpage = i, bookpage = ViewBag.BookCurrentPage })">@i</a>
                            </li>
                        }
                        <li class="page-item @(ViewBag.StudentCurrentPage == ViewBag.StudentTotalPages ? "disabled" : "")">
                            <a class="page-link" href="@Url.Action("Index", new { studentpage = ViewBag.StudentCurrentPage + 1, bookpage = ViewBag.BookCurrentPage })">Next</a>
                        </li>
                    </ul>
                </div>

            </div>
            
        </div>

        <!-- Books Section -->
        <div class="col-md-6">
            <div class="card">
                <h5 class="card-header">Books</h5>
                <div class="card-body">
                    <button class="btn btn-secondary float-right create-link" data-url="@Url.Action("Create", "books")">Create New</button>

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Page Count</th>
                                <th>Point</th>
                                <th>Author</th>
                                <th>Type</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.Books)
                            {
                               
                                <tr>
                                    <td>@item.name</td>
                                    <td>@item.pagecount</td>
                                    <td>@item.point</td>
                                    <td>@item.authors.name</td>
                                    <td>@item.types.name</td>
                                    <td>@item.Status</td>
                                </tr>
                            }
                        </tbody>
                    </table>




                    <!-- Pagination for Books -->
                    <div class="text-center">
                        <ul class="pagination">
                            <li class="page-item @(ViewBag.BookCurrentPage == 1 ? "disabled" : "")">
                                <a class="page-link" href="@Url.Action("Index", new { studentpage = ViewBag.StudentCurrentPage, bookpage = ViewBag.BookCurrentPage - 1 })">Previous</a>
                            </li>
                            @for (int i = Math.Max(1, ViewBag.BookCurrentPage - 2); i <= Math.Min(ViewBag.BookTotalPages, ViewBag.BookCurrentPage + 2); i++)
                            {
                                <li class="page-item @(i == ViewBag.BookCurrentPage ? "active" : "")">
                                    <a class="page-link" href="@Url.Action("Index", new { studentpage = ViewBag.StudentCurrentPage, bookpage = i })">@i</a>
                                </li>
                            }
                            <li class="page-item @(ViewBag.BookCurrentPage == ViewBag.BookTotalPages ? "disabled" : "")">
                                <a class="page-link" href="@Url.Action("Index", new { studentpage = ViewBag.StudentCurrentPage, bookpage = ViewBag.BookCurrentPage + 1 })">Next</a>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>




<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>


<script>
    $(function () {
        // Function to handle the "Create" button click
        $(".create-link").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url"); 

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });
    });

</script>